from __future__ import annotations

from datetime import datetime

from .analyzer import classify_topic
from .context import AuditContext


def sync_skills(corrections, context: AuditContext, dry_run=True, log=print):
    """Создать/обновить скиллы на основе найденных коррекций."""
    updated = 0
    created = 0
    topics_found = set()
    for correction in corrections:
        topics_found.update(classify_topic(correction["text"]))

    for topic in topics_found:
        if topic not in context.skill_topics:
            continue
        skill_info = context.skill_topics[topic]
        skill_name = skill_info["skill"]

        exists = False
        skill_dir = context.skills_dir / skill_name
        skill_path = skill_dir / "SKILL.md"
        for skill_file in context.skills_dir.rglob("SKILL.md"):
            try:
                content = skill_file.read_text()
                if f"name: {skill_name}" in content:
                    exists = True
                    skill_dir = skill_file.parent
                    skill_path = skill_file
                    break
            except Exception:
                continue

        if exists:
            if dry_run:
                log(f"  SKILL {skill_name}: exists, would check for updates")
                continue
            log(f"  SKILL {skill_name}: exists, up-to-date")
            continue

        if dry_run:
            created += 1
            log(f"  SKILL {skill_name}: would CREATE (topic: {topic})")
            continue

        skill_dir.mkdir(parents=True, exist_ok=True)
        content = f"""---
name: {skill_name}
description: Auto-generated by self-audit from dialog analysis.
---

# {skill_info["label"]}

Авто-сгенерирован {datetime.now().strftime("%Y-%m-%d")} на основе анализа диалогов с Нико.

## Контекст
Создан по результатам self-audit. Тема: {topic}.

## Правила
- Следовать указаниям Нико по этой теме
- Обновлять при новых находках в диалогах
"""
        skill_path.write_text(content)
        created += 1
        log(f"  SKILL {skill_name}: CREATED (topic: {topic})")

    if dry_run:
        if created == 0 and updated == 0:
            log("  Skills: no changes needed")
        elif created > 0:
            log(f"  Skills: {created} would be CREATED")
    elif created > 0 or updated > 0:
        log(f"  Skills: {created} created, {updated} updated")
    else:
        log("  Skills: all up-to-date")
    return created + updated
